"""Initial

Revision ID: d9443c0ee7f5
Revises: 
Create Date: 2024-09-24 23:07:03.968389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9443c0ee7f5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weatherdata',
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('wind_speed', sa.Float(), nullable=False),
    sa.Column('wind_direction', sa.String(), nullable=False),
    sa.Column('pressure', sa.Float(), nullable=False),
    sa.Column('precipitation_type', sa.String(), nullable=False),
    sa.Column('precipitation_amount', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weatherdata')
    # ### end Alembic commands ###
